production: false
version: 0.1.0
board_type: "local"
pin_name: "my-test-data"
filter_cols: !expr c("Sepal.Length", "Species")
status_ok: "OK"
status_review: "IN REVIEW"
status_accepted: "ACCEPTED"
status_rejected: "REJECTED"
data_reset: !expr datasets::iris
