production: true
version: 0.1.0
db_name: "postgres"
db_user: "postgres"
db_data_name: "table_editor_test"
db_admins_name: "admins"
admin_type_col: "channel"
admin_user_col: "user"
filter_cols: !expr c("Sepal.Length", "Species", "Petal.Length")
edit_cols: !expr c("Species")
hidden_cols: !expr c("Sepal.Length")
col_defs: !expr list(`Petal.Length` = colDef(
    html = TRUE,
    cell = JS(
      "function(cellInfo, state) {
        return `<span class=\"badge rounded-pill text-bg-primary\">${cellInfo.value}</span>`;
      }"
    )
  ))
page_size: 25
status_ok: "OK"
status_review: "IN REVIEW"
status_accepted: "ACCEPTED"
status_rejected: "REJECTED"
data_reset: !expr datasets::iris
