production: true
version: 0.1.0
db_name: "postgres"
db_user: "postgres"
db_data_name: "table_editor_test"
db_admins_name: "admins"
admin_type_col: "channel"
admin_user_col: "user"
filter_cols: !expr c("Sepal.Length", "Species")
edit_cols: !expr c("Species")
hidden_cols: !expr c("Sepal.Length")
status_ok: "OK"
status_review: "IN REVIEW"
status_accepted: "ACCEPTED"
status_rejected: "REJECTED"
